repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
      - id: check-toml
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.10
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--extend-select, "I", --fixable, "I,F", --fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: Clear output from Jupyter notebooks
        description: Clear output from Jupyter notebooks.
        files: \.ipynb$
        exclude: ^docs/pre_executed
        stages: [pre-commit]
        language: system
        entry: jupyter nbconvert --clear-output
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml
        description: Verify that pyproject.toml adheres to the established schema.
