# Same as Black
line-length = 120
indent-width = 4

[lint]
ignore = []

[lint.per-file-ignores] # Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
"swifttools/ukssdc/*.py" = ["E501", "F405", "E721", "F403", "E402"]
"swifttools/ukssdc/*/*.py" = ["E501", "F405", "E721", "F403", "E402"]
"swifttools/ukssdc/*/*/*.py" = ["E501", "F405", "E721", "F403", "E402"]
"swifttools/ukssdc/*/*/*/*.py" = ["E501", "F405", "E721", "F403", "E402"]
"examples/*.ipynb" = ["F704"]


[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
