# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Lint/Format check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check for Lint
        uses: astral-sh/ruff-action@v3

      - name: Check Formatting
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of uv

        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
      - name: Install Package
        # Note need to pip install -e so that coverage works correctly
        run: uv pip install -e .

      - name: Run tests
        run: pytest
